INSERT INTO items (name, label) VALUES
  ("boiteabijoux", "Boite a bijoux"),
  ("ecouteur", "Ecouteur"),
  ("phonetel", "Téléphone"),
  ("enceinte", "Enceinte"),
  ("soincheveux", "Soin pour cheveux"),
  ("boitedepreservatifs", "Boite de préservatifs"),
  ("console", "Consoles de jeux"),
  ("jouet", "Jouet pour enfant"),
  ("livre", "Livre"),
  ("bougie", "Bougie"),
  ("vesteencuir", "Veste en cuir"),
  ("pullbleu", "Pull bleu"),
  ("maquillage", "Trousse de maquillage"),
  ("soincheveux", "Soin pour cheveux"),
  ("dvd", "DVD"),
  ("vieuxjean", "Vieux Jean"),
  ("ordi", "Ordinateur portable"),
  ("string", "String"),
  ("radio", "Radio"),
  ("chaine", "Chaine"),
  ("casqueaudio", "Casque Audio"),
  ("montre", "Montre");
